let apple = new Apple(10);
let human = new Human("Em A", "Male", 50)
human.say("Ăn táo nào")
console.log(apple.getWeight())
console.log(human.getWeight())
human.eat(apple)
console.log(apple.getWeight())
console.log(human.getWeight())
console.log(human.getName())
console.log(human.getGender())
console.log(human.getWeight())